// user LOgin 
export const ADD_USER_LOADING = 'ADD_USER_LOADING'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_RESET = 'ADD_USER_RESET'

// sing up..
export const ADD_USER_SINGUP_LOGIN = 'ADD_USER_SINGUP_LOGIN'
export const ADD_USER_SINGUP_SECCESS = 'ADD_USER_SINGUP_SECCESS'
export const ADD_USER_SINGUP_FAIL = 'ADD_USER_SINGUP_FAIL'

// POST faecbook login... 
export const FAECBOOK_LODING = 'FAECBOOK_LODING'
export const FAECBOOK_SUCCESS = 'FAECBOOK_SUCCESS'
export const FAECBOOK_FAIL = 'FAECBOOK_FAIL'


export const ADD_LOGIN = 'ADD_LOGIN'
// user Logout...
export const ADD_LOGOUT = 'ADD_LOGOUT'



// userlist.. 
export const ADD_USERLIST_LOADING = 'ADD_USERLIST_LOADING'
export const ADD_USERLIST_SUCCESS = 'ADD_USERLIST_SUCCESS'
export const ADD_USERLIST_FAIL = 'ADD_USERLIST_FAIL'


// userid... 
export const ADD_USERID_LOADING ='ADD_USERID_LOADING'
export const ADD_USERID_SUCCESS = 'ADD_USERID_SUCCESS'
export const ADD_USERID_FAIL = 'ADD_USERID_FAIL'


// add adres... 
export const ADD_USER_ADRESS_LOADING = 'ADD_USER_ADRESS_LOADING'
export const ADD_USER_ADRESS_SUCCESS = 'ADD_USER_ADRESS_SUCCESS'
export const ADD_USER_ADRESS_FAIL = 'ADD_USER_ADRESS_FAIL'


// add Image... 
export const ADD_IMAGE = 'ADD_IMAGE'
export const ADD_LOADING = 'ADD_LOADING'
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL'



// POST CREATE
export const ADD_POST_USER_LOADING = 'ADD_POST_USER_LOADING'
export const ADD_POST_USER_SUECCSEE ='ADD_POST_USER_SUECCSEE'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'


// visa post. ... 
export const ADD_VISA_POST_LOADING = 'ADD_VISA_POST_LOADING'
export const ADD_VISA_POST_SUECCES = 'ADD_VISA_POST_SUECCES'
export const ADD_VISA_POST_FAIL = 'ADD_VISA_POST_FAIL'


// Update Post... 
export const ADD_POST_UPDATE_LOADING = 'ADD_POST_UPDATE_LOADING'
export const ADD_POST_UPDATE_SUCCESS = 'ADD_POST_UPDATE_SUCCESS'
export const ADD_POST_UPDATE_FAIL = 'ADD_POST_UPDATE_FAIL'

// delete post... 
export const ADD_POST_REMOVE_SUCCESS = 'ADD_POST_REMOVE_SUCCESS'
export const ADD_POST_REMOVE_LOADING = 'ADD_POST_REMOVE_LOADING'
export const ADD_POST_REMOVE_FAIL = 'ADD_POST_REMOVE_FAIL'


// post to user... hem sida... 
export const ADD_USER_POST_LOADING = 'ADD_USER_POST_LOADING'
export const ADD_USER_POST_SUCCESS = 'ADD_USER_POST_SUCCESS'
export const ADD_USER_POST_FAIL = 'ADD_USER_POST_FAIL'

// create post... 
export const ADD_USER_COMMENT_LOADING = 'ADD_USER_COMMENT_LOADING'
export const ADD_USER_COMMENT_SUCCESS = 'ADD_USER_COMMENT_SUCCESS'
export const ADD_USER_COMMENT_FAIL = 'ADD_USER_COMMENT_FAIL'

// delete comment
export const ADD_USER_COMMENT_DELETE_LOADING = 'ADD_USER_COMMENT_DELETE_LOADING'
export const ADD_USER_COMMENT_DELETE_SUCCESS = 'ADD_USER_COMMENT_DELETE_SUCCESS'
export const ADD_USER_COMMENT_DELETE_FAIL = 'ADD_USER_COMMENT_DELETE_FAIL'


// update comment from user... 
export const ADD_COMMENT_UPDATE_LOADING = 'ADD_COMMENT_UPDATE_LOADING'
export const ADD_COMMENT_UPDATE_SUCCESS = 'ADD_COMMENT_UPDATE_SUCCESS'
export const ADD_COMMENT_UPDATE_FAIL = 'ADD_COMMENT_UPDATE_FAIL'

// add LIKE ...
export const ADD_USER_LIKE_LOADING = 'ADD_USER_LIKE_LOADING'
export const ADD_USER_LIKE_SUCCESS = 'ADD_USER_LIKE_SUCCESS'
export const ADD_USER_LIKE_FAIL = 'ADD_USER_LIKE_FAIL'


// Follower... 
export const ADD_USER_FOLLOWE_LOADING = 'ADD_USER_FOLLOWE_LOADING'
export const ADD_USER_FOLLOWE_SUCCESS = 'ADD_USER_FOLLOWE_SUCCESS'
export const ADD_USER_FOLLOWE_FAIL = 'ADD_USER_FOLLOWE_FAIL'


// unFollower... 
export const ADD_USER_UNFOLLOWE_LOADING= 'ADD_USER_UNFOLLOWE_LOADING'
export const ADD_USER_UNFOLLOWE_SUCCESS = 'ADD_USER_UNFOLLOWE_SUCCESS'
export const ADD_USER_UNFOLLOWE_FAIL = 'ADD_USER_UNFOLLOWE_FAIL'


// google login 
export const ADD_USER_GOOGLE_LODING = 'ADD_USER_GOOGLE_LODING'
export const ADD_USER_GOOGLE_SUCESS = 'ADD_USER_GOOGLE_SUCESS'
export const ADD_USER_GOOGLE_FAIL = 'ADD_USER_GOOGLE_FAIL'




export const  ADD_STORY_LOADING = 'ADD_STORY_LOADING'
export const ADD_STORY_SUCCESS = 'ADD_STORY_SUCCESS'
export const ADD_STORY_FAIL = 'ADD_STORY_FAIL'